# This is a basic workflow to help you get started with Actions

name: AsciiDoc to PDF/HTML Converter

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  #This workflow contain a clean job that cancel previous workflow already running
  clean:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # Cancel previous workflow already running, to avoid interleaving on commit
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
    
  # This workflow contains a job called "build" witch creates pdf files
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Includes the AsciiDoctor GitHub Pages Action to convert adoc files to html and publish to gh-pages branch
      - name: asciidoctor-pdf-pages
        uses: INSPIRE-MIF/inspire-asciidoc-pdf-converter-action@v0.2.0
        with:
          # working_branch: main_release # branch to commit pdf
          asciidoctor_params: --attribute=nofooter
          # adoc_file_ext: .ascii # default is .adoc
          # pre_build:
          # post_build:
